### ISSUE TITLE
Define an application protocol

### ISSUE THREAD

**Issue by Forestierr** [Forestierr/dai-flappy-bird#1]
We need to define an application protocol for all network communications for our application.

**Comment by Forestierr** [comment]
For our protocol, I suggest using TCP on port 2000.

For all messages we can use a 4 character word to simplify the parsing of the data.

### Client

| Message | Description |
| --- | --- |
| INIT | Start the connection |
| STRT | Start the game |
| DIFF <difficulty> | Set the game difficulty |
| STAT | Get the score table |
| FLYY | Indicate that the bird is going to fly up |
| LOBY | Create a lobby |
| JOIN \<num\> | Join the lobby |
| LIST | List all existing lobby |
| PIPE \<position _y_\> | Place a new pipe |
| QUIT | Quit the game |

_LOBY_, _JOIN_, _LIST_, _PIPE_ is for multiplayer case.

### Server

| Message | Description |
| --- | --- |
| ACKK | Send an ACK to the client |
| START | Indicate that the game start |
| DATA / POSI / POSS / ?  | All the data to show on screen |
| EROR | Error message |
| DEAD | End of the game / death of flappy |

ACKK can be used for basic acknowledgement. For example, if a client has set a new difficulty, an ACK is sent to validate the change.

**Comment by Forestierr** [comment]
We need a response to the LIST message

**Comment by Forestierr** [comment]
Sequence diagram for 2 player, 1 player and full lobby scenario.

![DiagramSequence](https://github.com/user-attachments/assets/d8e0404e-4319-462d-9b02-1849df5d943a)

**Comment by Forestierr** [comment]
We also need to specify what type of data is transfert with the DATA message.
String / binary / string object ...

**Comment by A2va** [comment]
# Section 1 - Overwiew

The "Flap" protocol is a communication protocol that allows a client to connect to a server to play a Flappy Bird game.


# Section 2 - Transport protocol

The "Flap" protocol is a test based protocol. It uses TCP transport protocol and the port 2000 to communicate.
Every message must be encoded in UTF-8 and delimited by a newline character (\n). The messages are treated as text messages.


The communication must be established  by the client. Once the connection has been established, the server responds with `ACKK` to tell the client that it is ready.
It can send either `STRT` or `JOIN`.
* If the client send `STRT`, the game starts and the client can send `FLY` commands and the server responds with `DATA`
* If the client send `JOIN`, the server will create a lobby if there wasn't one, respond with a lobby id, then wait until a second client has joined the lobby. The second client can join the same lobby by providing a number to the `JOIN` command. 
One client will play the bird and send `FLY` command and the other will place the pipes with the `PIPE` command.


The client can quit the game at any time with the `QUIT` command.

# Section 3 - Messages

The client can send the following messages:

* `STRT`: The client is ready to start the game.
* `FLYY`: Indicate that the bird is going to fly up
* `PIPE <position y>`: Place a new pipe
* `JOIN <num>`: Join the lobby (num is optional, but without it will create a new lobby)
* `LIST`: List all existing lobby
* `QUIT`: Quit the game

The server can send the following messages:
* `ACKK`: Send an ACK to the client
* `DATA`: Send information to the client
* `EROR <message>`: Error message
* `DEAD`: End of the game / death of flappy

Common messages:
* `ACKK`: It is used by the server that it acknowledge the previous command of the client, if some information must communicated by the server the `DATA` cmd is used.
* `DATA`: This message is sent is in reponse to `FLYY`, `PIPE`, `JOIN`, `LIST`. For each information to pass a comma `,` must be used.
For `FLYY` and `PIPE` commands it look like this: `DATA B x y, P x y w, P x y w,...` where _B_ stands for Bird and _P_ for Pipe.
For the `JOIN` command: `DATA n` where _n_ is the lobby that was created by the command.
For the `LIST` command: `DATA n,o,p,...` where _n_, _o_, _p_ are all available lobby to join.

**Comment by Forestierr** [comment]
Just a quick note on the data commande, I think a simple modification would be a good idea.
`DATA B x y P x y w ... P x y w S s `
Where B represents Bird, P represents Pipe, and S represents the score.
(remove the coma and add the score)

**Comment by A2va** [comment]
But isn't it more easy to parse with the comma because we can split(",") and get all attributes for the bird and pipe separetely.

**Comment by Forestierr** [comment]
#21
